### ISSUE TITLE
Bring FreeBMD2 to accessibility standard

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#10]

**Comment by richpomfret** [comment]
Possible task for our UX'ers?

**Comment by richpomfret** [comment]
@DeniseColbert to devise list of stories to go into the Accessibility epic - include feedback audit report from FR and list any outstanding actions/items (if we can test or ensure they are flagged to be tested).

**Comment by DeniseColbert** [comment]
- [ ] **STAS-F10: Non-Descriptive Page Titles** #926 CLOSED
- [ ] **STAS-F03: Empty Links** CLOSED
- [ ] **STAS Review and adjust the search results page for accessibilty** Accessibility Review Actor: researcher CLOSED
- [ ] **Review and adjust the search form page for accessibility** Accessibility Review Actor: researcherCLOSED
- [ ] **STAS Review and adjust the search results detail page for accessibility** Accessibility Review Actor: researcher CLOSED
- [ ] **STAS-F07: Areas Inaccessible via Keyboard** Accessibility Review HTML CLOSED

*****************************************

- [ ] **STAS Review and adjust the about search results page for accessibility** Accessibility Review ready #965 1.7 Researchers Product Backlog

- [ ] **STAS-F01: Missing ‘Skip’ Navigation** Accessibility Review P0 ready #917 1.4 Researchers Product Backlog

- [ ] **STAS-F02: Incorrect Heading Structure** Accessibility Review HTML P0 ready #918 1.4 Researchers Product Backlog

- [ ] **STAS-F04: Inappropriate use of Fieldsets** Accessibility Review CSS FORM P0 ready #920 1.4 Researchers Product Backlog

- [ ] **STAS-F05: Missing Form Labels** Accessibility Review CSS FORM P0 ready #921 1.4 Researchers Product Backlog

- [ ] **STAS-F06: Orphaned Form Label** Accessibility Review CSS FORM P0 ready #922 1.4 Researchers Product Backlog

- [ ] **STAS-F08: HTML Markup Errors** Accessibility Review HTML P0 ready #924 1.4 Researchers Product Backlog

- [ ] **STAS-F09: Duplicate ID’s** Accessibility Review CSS FORM P0 ready #925 1.4 Researchers Product Backlog

- [ ] **STAS-F11: Non-Descriptive Alt Text** Accessibility Review HTML P0 ready #927 1.4 Researchers Product Backlog

- [ ] **STAS-F12: Data Tables with Incorrect Markup** Accessibility Review CSS HTML P0 ready #928 1.4 Researchers Product Backlog

- [ ] **STAS-F13: Illogical Tab Order** Accessibility Review HTML P0 ready #929  1.4 Researchers Product Backlog

- [ ] **STAS-F14: Links not Visible in Focus** AA Accessibility Review CSS P0 ready #930  1.4 Researchers Product Backlog

- [ ] **STAS-A02: Visual Cue on Keyboard Focus** Accessibility Review CSS P0 ready #932 1.4 Researchers Product Backlog

- [ ] **STAS-A03: Links not Understood out of Context** Accessibility Review HTML P0 ready #934 1.4 Researchers Product Backlog

- [ ] **STAS-A04: Users not notified of Links Opening in a new Window** Accessibility Review HTML P0 ready #935 1.4 Researchers Product Backlog

- [ ] **20 STAS-F15: Insufficient Colour Contrast** AA Accessibility Review CSS P20 Systemwide epic in progress #931 1.4 Researchers On Ice

- [ ] **STAS-A01: Accessibility Statement (Review and Update)** Accessibility Review Actor: executive P11 documentation ready #933 1.4 Researchers Product Backlog

**Comment by PatReynolds** [comment]
Hi @AlOneill could you have a look at these stories, and say which are already complete on multi-modal, which need to be fixed at the multi-modal level, and which on a site-by-site base.

Which are CSS?  Which are html?  Which are Ruby, and what else?  We can then allocate to developers and other volunterers (almost certiainly not you or I until it gets to testing, at least.

**Comment by richpomfret** [comment]
@jayto581 perhaps this might be something you could take a look at? We need an accessibility review to see if we have covered key requirements. @PatReynolds to discuss with you.

**Comment by AlOneill** [comment]
As far as the colours are concerned, all colour-combinations (font and background) are now accessible provided our base CSS styles are used — i.e. the styles defined in the Inuit-based style-sheets (at the time of the colour updates). However, there are a number of other style-sheets in use, particularly on FreeBMD, which I cannot vouch for.

As for stories that relate to markup, the specific instances highlighted by the Shaw report were fixed at the time. However, our pages have been modified since then and I cannot say with certainty that they still comply with accessibility standards. Further, If a get a chance to review a page, then I'm likely to find something that needs attention (recent examples include, no obvious focus state for a 'new' button; poor link text, invalid address for a link — # by itself will not work for a keyboard-only user as the focus will not move to an invalid `href`).

Items that have **not been fixed** include: missing Skip-links, some instances of Illogical Tab Order, and some instances of missing warnings that a link will open in a new window or tab.

**Comment by richpomfret** [comment]
@AlOneill we can create separate stories for these things that have not been fixed, or (if they are small/quick) we can keep them here. I think the former would be preferable, it would also be ideal to have an Accessibility review meeting scheduled in soon.

**Comment by richpomfret** [comment]
Discussion on requiring a sign-off process for pages ahead of them being 'ready' for a accessibility review.

**Comment by PatReynolds** [comment]
Not sure what your comment of 15th Feb means, Rich.  We do have a sign off process for pages already.  We can add specific accessibility issues to the checklist, if that's what is meant (sounds like a good way forwards).

**Comment by PatReynolds** [comment]
Draft checklist https://docs.google.com/document/d/1V4BxoDRamp3CW9wTVlzEJOoputqhcFKiaqIqgLX-Gwg/edit?usp=sharing - what do you think, Alison?

**Comment by richpomfret** [comment]
@AlOneill can you review?

**Comment by AlOneill** [comment]
Have added a few items and made some comments.

**Comment by richpomfret** [comment]
@PatReynolds to take a look at the comments. To then consider next steps.

**Comment by PatReynolds** [comment]
All comments good. 

@AlOneill can you add Skip-links info and the use of the international "opens on a new page" symbol to the Markup page?

**Comment by AlOneill** [comment]
@PatReynolds There is no such thing as an 'opens in a new ****' symbol: for instance, Wikipedia uses it to mean only that the link is to an external site. Is that what you want me to add, that there is no such symbol?

As for Skiplinks, our pages do not currently have even the most important one, at the very top of the page. In any case, this would be added automatically, outside of Refinery. (Use of additional Skiplinks to bypass adverts and sub-navigation is complicated — we do not have a plan for these.) I do not know what info you want me to add.

**Comment by PatReynolds** [comment]
This is from the Accessibility Proofing Checklist - https://docs.google.com/document/d/1V4BxoDRamp3CW9wTVlzEJOoputqhcFKiaqIqgLX-Gwg/edit#heading=h.fp07a3gdo0gs

![image](https://user-images.githubusercontent.com/6338822/132312198-c42ec534-df52-41f4-88c7-93cc924bea88.png)

**Comment by AlOneill** [comment]
Comment added re non-existence of the "international symbol" to Accessibility checklist — my original comment re the existence of such a symbol had been deleted.

**Comment by DeniseColbert** [comment]
Not sure what happened to your comment @AlOneill , but yes, this needs removing from the checklist

**Comment by PatReynolds** [comment]
Skipping adverts is most important: @PatReynolds to ask webaim for advice/examples of websites displaying adverts that use skiplinks approrpritely.

Skipping the menu is of lesser importance

**Comment by DeniseColbert** [comment]
@PatReynolds to ask WebAIM for examples of websites that have ads and use skip-links

**Comment by PatReynolds** [comment]
Emailed 10 Jan 2022

**Comment by PatReynolds** [comment]
Asked the Adsense community 24 Jan 2022

**Comment by PatReynolds** [comment]
Got one reply from WebAIM but it was about the correct technical use of skip links, not about what Google thinks of them, so have asked again.

Asked the GoogleAds community 7 Jan 2022

**Comment by richpomfret** [comment]
To discuss in the doc team meeting - to break this down into smaller stories (as appropriate).

**Comment by PatReynolds** [comment]
Comments from WebAIM:
"WebAIOIM: 2.4.1 says that a mechanism is available to bypass blocks of content that
are repeated on multiple Web pages.  So are your adverts repeated on every
page such that they would be part of the "blocks of content" to skip over?
If they only appear on the homepage, then you might not have to skip over
them since they're not repeated."
"As far as how it affects google, that
indeed is a question for a different forum but I'm not sure that part of
the question is relevant.  That is, how it affects them should not be a
deciding factor in whether you do it.  If you have content that is repeated
on all pages, then you need a way to jump over that content."

Adsense support ticket: Ticket ID: 5-6797000032089.

**Comment by AlOneill** [comment]
@PatReynolds @DeniseColbert 
This issue strikes me as really being two, unrelated system-wide issues, but I will comment here for now.

I've been looking at how we might implement a skiplink at the top of every page and need to confirm our requirements. As I remember it, we want a "skip to main content" link that is invisible until brought into focus with a press of the tab key. The standard position, on focus, is top-left, with styling that makes it easy to spot. Is this what we want?

**Comment by PatReynolds** [comment]
Asked again - Ticket ID: 4-2903000032475.

**Comment by PatReynolds** [comment]
Andwer "you can use skiplinks as long as these are in compliance with the AdSense Ad placement policies" - which they are.

**Comment by PatReynolds** [comment]
Focus never goes to adverts on test3?

On Beta, goes, but it is  not clear what the focus is.

**Comment by DeniseColbert** [comment]
Initial skiplink is due for beta and the rest can be done for a later phase

**Comment by Vino-S** [comment]
Deployed

**Comment by AlOneill** [comment]
Wow — a proper skiplink in progress. Grand!

These are my initial observations:
1. I had to press tab key twice to see the skiplink — I would expect one press to be enough
2. when selected on Database page, it skipped to the BMD logo — it should skip to the h1 or thereabouts
3. on the Search page it skipped to the beginning of the form — correct
4. on page load the skiplink is not fully hidden — see image

<img width="384" alt="Image" src="https://github.com/user-attachments/assets/53e2785a-5230-4ad7-be07-ea904b2d7916" />

**Comment by Vino-S** [comment]
Thanks Alison,
Made some more changes and its on test3 for testing

**Comment by AlOneill** [comment]
@Vino-S The first press of the Tab key now reveals the skiplink (on test3). Thank you!

@richardofsussex 
Something weird is happening on the About page, for example:

<img width="1728" height="1117" alt="Image" src="https://github.com/user-attachments/assets/d588c3d9-3d56-4ab2-a152-fd37715fd2ad" />

1. note the odd shape of the focus box 
2. the top "On this page" menu item is one colour; the next item is another colour — why?
3. why is there an `h2` immediately after the `h1` with more or less the same wording?
4. the heading hierarchy is broken: `h1` then `h5` then `h2`
5. why has "On this page" been demoted to `h5`? The original `h2` made much more sense and does not break the hierarchy
6. the page is still **largely inaccessible to screen reader users** — I thought this pattern was being dropped
7. there are 2 blind presses (no indication of which element has focus) of Shift+Tab between the item shown in focus and "About FreeBMD" in the main menu — not good
8. the source order appears to place the "On this page" menu directly after the `h1` whereas the opening paragraph(s) was designed to intervene, to give some breathing space, if you like, and reassure the user that they are in the right place — the source order is how a mobile phone user will see the page

**Comment by richardofsussex** [comment]
@AlOneill a number of your comments (1, 2, 4, 5, 6) relate also to the new Help framework, which I have simply re-used when including the About pages which we decided should be in the MVP. In particular, I strongly agree with your point 6.

I noticed yesterday that while the links within 'On this page' are to a URL like 'https://beta.freebmd2.org.uk/help/about_freebmd', and these work within the page, you can't type that URL into the address bar and just go to that section of the About help. This strikes me as wrong. @Vino-S and I are going to have to sort out a strategy which follows 'the Rails way' and standard web conventions.

**Comment by richardofsussex** [comment]
Right ... the Help and About sections have been completely refactored so that each page is a separate HTML document, with its own address/URL. This should resolve the accessibility issues caused by the previous Javascript-based strategy. 

From the user's perspective, the pages should look and behave much the same as before (except that a new page will be fractionally slower to load).

We now need to go through the other pages, and where there is a link to a help page it should now include the full URL of that help section, rather than just '/help' (or '/about'). From the user's perspective this will be a win, since they will be taken straight to the help they were seeking, rather than having to cast around for it within the Help section.

I've asked @Vino-S to load this code to test3 - she will doubtless tell us when it's up there for checking.

**Comment by richardofsussex** [comment]
I've done the link updating for the three obvious help links I could find (search, results, entry information).

**Comment by richardofsussex** [comment]
The updated Help and About sections are now available for review on test3.

**Comment by KristinaGadzhieva** [comment]
@AlOneill could you please check skiplinks ?

**Comment by AlOneill** [comment]
Nothing has changed since I last checked the skiplinks: 

- on Beta it takes 2 presses of the Tab key to reveal the skiplink which is not as expected — one press should be enough
- on test3 the skiplinks work as expected, i.e. they appear with the first press of the Tab key

It is the pages themselves that are not working for screen reader users. I'm confused by the navigation (or lack of it) and I can _see_ when using a screen reader.

**Comment by Vino-S** [comment]
Skiplinks deployed to beta

**Comment by KristinaGadzhieva** [comment]
@AlOneill could you please check Beta once again?

**Comment by AlOneill** [comment]
On beta the first press of the Enter key moves the focus to the "Privacy" link at the bottom right of the screen. The second press moves the focus to the skiplink in the top left of the screen.

Looking at the page source, the "Privacy" link comes before the skiplink.

**Comment by AlOneill** [comment]
I further note that the "Privacy" link takes one to a Cookie Consent window and that the link remains even after responding to that window. Privacy and Cookie Consent are related, but they are not the same thing. I do not believe that window should be allowed to interrupt the functioning of the skiplink.

Also, because the "Privacy" link is bottom right on the screen, it is not obvious to anyone expecting to see a skiplink top left.

**Comment by KristinaGadzhieva** [comment]
@Vino-S could you please have a look at Alison's comments?

**Comment by KristinaGadzhieva** [comment]
All changes have been deployed. @Vino-S will work on Alison's comments when she is back (on September)
