### ISSUE TITLE
Laundry list for Header & Footer

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#155]
- [ ] More space around FreeBMD logo needed, per mock-up
- [ ] Menu bar links need spacing out and correct font
- [ ] Github icon link points to correct page

**Comment by AlOneill** [comment]
The footer link to "Statistics" still goes to the **BMD1** page, whereas it should now point at our new Records section, yes? Having said that, I'm thinking that the markup for that part of the footer should be tweaked somehow to be clearer for S-R users.

**Comment by AlOneill** [comment]
Maybe move the Statistics box in the footer to the Records page, similar to as done on REG. This would leave more space for useful links, such as to our Accessibility Statement …

**Comment by janetkwakye-afk** [comment]
We have discussed this epic and agreed that the key requirements have been met, so it can now be closed. We will, however, continue to make improvements as we receive further feedback from users.
