### ISSUE TITLE
District data (for records page)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeBMD2#463]
An issue/group of issues identified in other stories and brough together here 
- [ ] Philip: I just looked at one record, at the bottom of my screen - Hammersmith - which gives its dates of existence and the number of records transcribed. The Dates were "existing from 1915 to 2000"; then I looked at the 'bible' that I use: Hammersmith: created 1.7.1913 out of Fulham R.D. Abolished 1.1.2001 and registers transferred to 
 - [ ] Hammersmith and Fulham (which started on 1.1.2001). I then looked at Fulham R.D. (on test3) - existing from 1875 till 2000. My 'bible' , written by Brett Langston, which states Fulham was created 1.4.1875 out of Kensington RD'.  So it looks to me that the dates of existence are being generated from the FreeBMD database itself rather from actual dates. Not a problem, as long as we make that clear. We are not transcribing records any newer than 1991 or 1992 (as appropriate) so we don't have many newer records, which tend to come from one-name studies - hence we don't yet have a Hammersmith and Fulham District on that page.
 - [ ] Re @PhilipClarke712 's concern about the source of the content (our database or another source) - need to add line at the top "This data is derived from the FreeBMD database" (do you think that is ok @PhilipClarke712 - [please suggest something better).
 - [ ] I have suggested what is, in effect, a "small print" paragraph to go under the table because Districts may, and do, get created during one of these major periods and also they may be replaced by another District during a different major period. So if the search criterion has a single district specified as per Hambledon above - it was abolished on 1st April 1935 and the registers transferred to Surrey South Western (Surrey S W.) - you will not find all the "hits" that you would expect to find. So, to be sure of finding all the "hits" in the town of Hambledon, in the period 1852 to 1945, as specified above, your search needs to be in both Hambledon and Surrey S. W.

**Comment by PhilipClarke712** [comment]
**Part 1:**

In trying to formulate an answer to the question, I went back to test3 https://test3.freebmd.org.uk/districts/alphabet_selection?locale=en selected H  to get to a page for **Hammersmith** (see extract)
![Screenshot 2022-01-24 122949](https://user-images.githubusercontent.com/67054943/150783432-b1956ee8-1abb-45f7-8e66-97f61dc6c6bb.png)  which states Hammersmith existed from 1915 to 2000

I then click on the hyperlink which takes me to 
![Screenshot 2022-01-24 123440](https://user-images.githubusercontent.com/67054943/150784205-e07cfb1e-06c2-4ba2-9051-8efa79520161.png)

If we work up the page, from the bottom: Volumes 12, 5b and 5c are correct for their time period. 

Volume 1a is more of a problem it covers the time period 1852 to 1945, so there is a date-conflict between what is on "H" {results} page for **Hammersmith** and what is on the {Entry information Page} **District Information: Hammersmith** page. Note Hammersmith RD was formed on the 1/7/1913 out of Fulham RD (created 1/5/1875 and abolished in 1/1/2001; when Hammersmith and Fulham were combined); and Fulham RD was created out of Kensington RD (created 1/7/1837 and abolished in 1/7/1981).

So if we wanted to search records from the "place" known as Hammersmith we could search Volumes 1a, 5c, 5b and 12.  That would / should gives us "hits", but we would be searching Kensington RD, Fulham RD and Hammersmith RD, amongst others.

**Out-take on the use of Volume xx**: The table appears (without stating it) to use a Volume number of **xx** to mean - does not exist; but between 1837 and 1851 Volume xx (or 20) was a valid volume number in that timeframe - it was one of the Lancashire Volumes, it covered Manchester, Liverpool, Oldham, etc, and  Hammersmith has never in that part of the country. Note: having looked at the page for Manchester, Volume 20 is used for the period 1837 to 1851, whereas the GRO used the Roman version xx. On BMD1 we say that Roman and numerals can be used interchangeably for Volume number (that was put into draft pages but I'm not sure if it is in live pages on BMD2) . Note: Manchester got spilt into North and South and was then combined, so there are are lots of Volume xx - this could be addressed with a simple note: Volume xx means a district of this name did not exist in this time frame (or words of that effect). Otherwise, any expecting Roman Volume numbers in the period 1837 to 1851 and numerals afterwards , might be confused.

**Speculation on data-sets in the data base:** I've never seen the data base, so this is all speculation. It is likely that the data base has  one or four data set(s) of tables that relate volume number to Registration District - the GRO had four reorganisations of its Volumes between 1837 and 1974. So the tables that populate the District Information Page: Hammersmith have been taken from that data-set in the table base. They use the time frame that the Volume numbering was in existence, not necessarily the time frame that this district existed.

**Comment by DeniseColbert** [comment]
To revive when closer to/in Records page sprint

**Comment by richardofsussex** [comment]
This story is primarily about the design of the database and the effect of this design on search strategies. For example, the wide ranges of dates for volume numbers are a fixed part of the database design. Clearly, these wide date ranges will fail to capture changes to Districts which occurred during one period. I am quite happy with the idea of a disclaimer that the information provided is derived from our database, but I don't think we can go further than this for MVP.

**Comment by KristinaGadzhieva** [comment]
To investigate writing a disclaimer or information for Help page

**Comment by richardofsussex** [comment]
I have re-jigged the District page in a number of ways in an attempt to make things clearer:

- the UKBMD paragraph has been moved to the end, after all the (useful) information we provide
- the start and end date for the District are explicitly stated (why weren't they before?)
- an explanatory paragraph has been added below the volumes table
- the last line of the volumes table has been dropped: it contained incorrect information
- Other information has been reformatted into a table

The result is now on beta; please check and comment.

**Comment by AlOneill** [comment]
Just one small observation: by putting the whole table in the `tbody` element, the styling is not quite right: the top border of the table is heavier than the other borders. Try putting the header row in a `thead` element and see the difference.

**Comment by AlOneill** [comment]
@richardofsussex 
Looks and markup now as expected. Thank you.
