### ISSUE TITLE
Single sign-on ability

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeBMD2#539]
Across all sites, but to be developed on FreeBMD2 as it's a blank slate

- [ ] Create a specification document for discussion 
- [ ] Create a fourth database which will contain a collection for all UserIDs
- [ ] Design (UX team) the pages/pathways for registering and Logging in for Researchers and Volunteers

**Comment by janetkwakye-afk** [comment]
We have reviewed this epic and confirmed that it meets the agreed requirements. It can therefore be closed.
